version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: recommender
      POSTGRES_PASSWORD: recommender
      POSTGRES_DB: recommender
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  recommender:
    build:
      context: ./ZertuRecommender
      dockerfile: Dockerfile
    environment:
      - "CONNECTION_STRING=Host=db;Database=recommender;Username=recommender;Password=recommender"
#    volumes:
#      -  recommender-data:/app/Data
#      -  recommender-data:/app/Uploads
    ports:
      - "80:80"
    depends_on:
      - db
volumes:
  recommender-data:
  postgres-data:
      
      
